--- # Ansible playbooks start with ---

# Each one of these outermost blocks is a "play". This file contains a single,
# anonymous play with three tasks.

- hosts: all   # Similar to 'ansible all ...' for the ad-hoc commands
  become: true # Same as --become for the ad-hoc commands
  tasks:

  # Tasks are executed in order from top to bottom

  - name: Update repo index # Task names should be decsriptive
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" # 'when' is like conditional compilation
                                           # for Ansible: this task only runs when
                                           # the condition is true. The syntax for
                                           # 'when' expressions is the same as Jinja2
                                           # expressions.
                                           #
                                           # Variables like 'ansible_distribution' come
                                           # from the gather_facts module.

  - name: Install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Add PHP support for Apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
