---

- hosts: webservers
  become: true
  tasks:

  - name: Remove Apache and PHP
    apt:
      name:
        - "{{ apache }}"
        - "{{ php }}"
      state: absent
    when: ansible_distribution == "Ubuntu"
