---

- hosts: all
  become: true
  pre_tasks:
  - name: Update repository cache
    tags: always
    apt:
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  roles:
  - base # Looks for a taskbook in 'roles/{role name}/tasks/main.yml'

- hosts: workstations
  become: true
  roles:
  - workstations

- hosts: webservers
  become: true
  roles:
  - webservers

- hosts: db
  become: true
  roles:
  - db

- hosts: files
  become: true
  roles:
  - files
