--- # Ansible playbooks start with ---

# Each one of these outermost blocks is a "play".
# This file contains three (anonymous) plays.

- hosts: all   # Similar to 'ansible all ...' for the ad-hoc commands
  become: true # Same as --become for the ad-hoc commands
  pre_tasks:   # 'pre_tasks' instead of 'tasks' mandates that these tasks run before any other do
  # Tasks are executed in order from top to bottom
  - name: Install updates
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu" # 'when' is like conditional compilation
                                           # for Ansible: this task only runs when
                                           # the condition is true. The syntax for
                                           # 'when' expressions is the same as Jinja2
                                           # expressions.
                                           #
                                           # Variables like 'ansible_distribution' come
                                           # from the gather_facts module.

- hosts: webservers # Only runs on hosts part of the "webservers" group (see inventory)
  become: true
  tasks:
  - name: Install Apache and PHP
    apt:
      name:
        # We can parameterize playbooks with variables. In this case, we want to
        # parameterize, rather than hard code, the names of the packages to install
        # for Apache and PHP. This is useful if this playbook is being run on
        # multiple hosts running different distros where the package names for
        # Apache and PHP may differ slightly. We specify the values of these
        # variables in the inventory, but that is just one of many ways of setting variables.
        - "{{ apache }}"
        - "{{ php }}"
      state: latest

- hosts: db
  become: true
  tasks:
  - name: Install MariaDB
    apt:
      name: mariadb-server
      state: latest

- hosts: files
  become: true
  tasks:
  - name: Install Samba
    package: # The 'package' module is a distro-agnostic module for installing packages
      name: samba
      state: latest
