--- # Ansible playbooks start with ---

# Each one of these outermost blocks is a "play".
# This file contains three (anonymous) plays.

- hosts: all   # Similar to 'ansible all ...' for the ad-hoc commands
  become: true # Same as --become for the ad-hoc commands
  pre_tasks:   # 'pre_tasks' instead of 'tasks' mandates that these tasks run before any other do
  # Tasks are executed in order from top to bottom
  - name: Install updates
    tags: always # Built-in tag name that means this task should always run unless specified otherwise
    apt: # The 'apt' module uses apt to install packages. Obviously only works on Debian-based distros
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu" # 'when' is like conditional compilation
                                           # for Ansible: this task only runs when
                                           # the condition is true. The syntax for
                                           # 'when' expressions is the same as Jinja2
                                           # expressions.
                                           #
                                           # Variables like 'ansible_distribution' come
                                           # from the gather_facts module.

- hosts: workstations
  become: true
  tasks:
    - name: Install unzip
      package: # The 'package' module is a distro-agnostic module for installing packages
        name: unzip

    - name: Install Terraform
      unarchive: # The 'unarchive' module unzips a Zip archive given a file path or URL
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes # Tells Ansible that src is a URL, not a file path
        mode: 0755
        owner: root
        group: root

- hosts: webservers # Only runs on hosts part of the "webservers" group (see inventory)
  become: true
  tasks:
  - name: Install Apache and PHP
    tags: apache,apache2,ubuntu
    apt:
      name:
        # We can parameterize playbooks with variables. In this case, we want to
        # parameterize, rather than hard code, the names of the packages to install
        # for Apache and PHP. This is useful if this playbook is being run on
        # multiple hosts running different distros where the package names for
        # Apache and PHP may differ slightly. We specify the values of these
        # variables in the inventory, but that is just one of many ways of setting variables.
        - "{{ apache }}"
        - "{{ php }}"
      state: latest
  - name: Remove Apache and PHP
    tags: never # Built-in tag name that means this task should never run unless specified otherwise
    apt:
      name:
        - "{{ apache }}"
        - "{{ php }}"
      state: absent
    when: ansible_distribution == "Ubuntu"
  - name: Copy default HTML file for site
    tags: apache,apache2
    copy: # The 'copy' module copies files ... duh!
      src: default_site.html # Looks under files/ directory by default
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db
  become: true
  tasks:
  - name: Install MariaDB
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest

- hosts: files
  become: true
  tasks:
  - name: Install Samba
    tags: samba
    package:
      name: samba
      state: latest
