---

- name: Install Apache and PHP
  tags: apache,apache2,ubuntu
  package:
    name:
      - "{{ apache }}"
      - "{{ php }}"
    state: latest

- name: Remove Apache and PHP
  tags: never
  apt:
    name:
      - "{{ apache }}"
      - "{{ php }}"
    state: absent

- name: Change email address for admin
  tags: apache
  lineinfile:
    path: /etc/apache2/sites-enabled/000-default.conf
    regexp: '^\tServerAdmin'
    line: "\tServerAdmin somebody@somewhere.net"
  notify: restart_apache # restart_apache handler for if this is changed

- name: Copy default HTML file for site
  tags: apache,apache2
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
